[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  NETLIFY_NEXTJS_RUNTIME_PATCH = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
